# Setup

In [1]:
import tensorflow as tf
from tensorflow import keras

2022-05-18 11:21:10.930668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-18 11:21:10.930691: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


# Tensors

In [2]:
x = tf.constant([[5,2],[1,3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


2022-05-18 11:21:13.279244: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-05-18 11:21:13.279287: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-05-18 11:21:13.279322: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (MPC): /proc/driver/nvidia/version does not exist
2022-05-18 11:21:13.279638: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
x.numpy()

array([[5, 2],
       [1, 3]], dtype=int32)

In [4]:
print("dtype:",x.dtype)
print("shape:",x.shape)

dtype: <dtype: 'int32'>
shape: (2, 2)


In [5]:
print(tf.ones(shape=(2,1)))
print(tf.zeros(shape=(2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [6]:
x = tf.random.normal(shape=(2,2), mean=0.0, stddev=1.0)
y = tf.random.uniform(shape=(2,2), minval=0, maxval=20, dtype='int32')
print(x,'\n',y)

tf.Tensor(
[[-1.4200552   0.7519918 ]
 [-0.23922898 -0.6219654 ]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[13 17]
 [10  3]], shape=(2, 2), dtype=int32)


# Variables

In [7]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.12177394, -0.57344025],
       [ 0.15359516, -0.9315638 ]], dtype=float32)>


In [8]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)

for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] #assert verification egalité
        
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j]

subbed_value = tf.random.normal(shape=(2,2))
a.assign_sub(subbed_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j] - subbed_value[i,j]

# Math

In [9]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a,'\n',b)

c = a+b
d = tf.square(c)
e = tf.exp(d)

aprime = tf.constant([[5,2],[1,3]], dtype='float32')
aprime = aprime+b
print(aprime)

tf.Tensor(
[[ 2.0168335  -0.81263673]
 [ 0.6760165   1.4286938 ]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[-0.39479575  0.55874693]
 [ 0.32157645 -0.95124984]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[4.605204  2.5587468]
 [1.3215765 2.0487502]], shape=(2, 2), dtype=float32)


# Gradient

In [10]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a,'\n',b)

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    print(c)
    dc_da = tape.gradient(c,a)
    print(dc_da)
    
print(a*tf.pow((tf.square(a)+tf.square(b)),-0.5)) #pow(x,y)=x^y

tf.Tensor(
[[-0.22894487  0.23692997]
 [ 0.984966   -2.59272   ]], shape=(2, 2), dtype=float32) 
 tf.Tensor(
[[-0.8586488  -0.3594692 ]
 [ 0.9539174  -0.11772922]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.888647  0.4305275]
 [1.3711734 2.5953915]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.2576331  0.5503248]
 [ 0.718338  -0.9989706]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.2576331  0.5503248]
 [ 0.7183381 -0.9989706]], shape=(2, 2), dtype=float32)


Variable sont watch automatiquement

In [11]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
    c = tf.sqrt((tf.square(a)+tf.square(b)))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.2576331  0.5503248]
 [ 0.718338  -0.9989706]], shape=(2, 2), dtype=float32)


In [12]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_da2= outer_tape.gradient(dc_da,a)
    print(d2c_da2)
    
print(tf.square(b)/pow(tf.square(a)+tf.square(b),3/2))

tf.Tensor(
[[1.0506142e+00 1.6192753e+00]
 [3.5297540e-01 7.9277158e-04]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.0506142e+00 1.6192753e+00]
 [3.5297540e-01 7.9279311e-04]], shape=(2, 2), dtype=float32)


# Keras layers

Classe self/super

In [13]:
class Animal(object):
     def __init__(self, speed, is_mammal):
          self.speed = speed
          self.is_mammal = is_mammal

class Cat(Animal):
     def __init__(self, is_hungry):
          super().__init__(10, True)
          self.is_hungry = is_hungry

barry = Cat(True)
print(f"speed: {barry.speed}")
print(f"is a mammal: {barry.is_mammal}")
print(f"feed the cat?: {barry.is_hungry}")

speed: 10
is a mammal: True
feed the cat?: True


Simple Layer:

In [14]:
class Linear(keras.layers.Layer):
    """y = w.x +b"""
    
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(initial_value=w_init(shape=(input_dim,units),dtype='float32'), trainable=True,)
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(initial_value=b_init(shape=(units,),dtype='float32'),trainable=True)
        
    def call(self, inputs):
        return tf.matmul(inputs, self.w)+self.b

In [15]:
units=4
input_dim=2
linear_layer = Linear(units, input_dim)
print(linear_layer.w)

one=tf.ones((2,input_dim))
print(one)

y = linear_layer(one)
assert y.shape == (2,units)

print(y)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.03816874, -0.06693512,  0.04210206, -0.0053341 ],
       [-0.00680374,  0.03030141, -0.10571864, -0.04916116]],
      dtype=float32)>
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.04497248 -0.03663371 -0.06361657 -0.05449526]
 [-0.04497248 -0.03663371 -0.06361657 -0.05449526]], shape=(2, 4), dtype=float32)


In [16]:
assert linear_layer.weights == [linear_layer.w, linear_layer.b]
print(linear_layer.weights)

[<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.03816874, -0.06693512,  0.04210206, -0.0053341 ],
       [-0.00680374,  0.03030141, -0.10571864, -0.04916116]],
      dtype=float32)>, <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]


# Layer weight creation

In [17]:
class LinearV2(keras.layers.Layer):
    """y = w.x +b"""
    
    def __init__(self, units=32, input_dim=32):
        super(LinearV2, self).__init__()
        self.units = units
        
    def build(self,input_shape):
        self.w = self.add_weight(shape=(input_shape[-1],self.units),initializer='random_normal',trainable=True)
        self.b = self.add_weight(shape=(self.units,), initializer='random_normal', trainable=True)
        
    def call(self, inputs):
        return tf.matmul(inputs, self.w)+self.b
    
linear_layerV2 = LinearV2(4)


y = linear_layerV2(tf.ones((2,2)))
print(y)
print('\n')
print(linear_layerV2.weights)

tf.Tensor(
[[-0.03043097  0.02160225 -0.06658838 -0.01473466]
 [-0.03043097  0.02160225 -0.06658838 -0.01473466]], shape=(2, 4), dtype=float32)


[<tf.Variable 'linear_v2/Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.07363174, -0.02516892,  0.02963506,  0.03630914],
       [ 0.06342369,  0.01021558, -0.06788558, -0.01085989]],
      dtype=float32)>, <tf.Variable 'linear_v2/Variable:0' shape=(4,) dtype=float32, numpy=array([-0.02022291,  0.0365556 , -0.02833787, -0.04018391], dtype=float32)>]


# Layer Gradients

In [36]:
#dataset
(x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices((x_train.reshape(60000,784).astype('float32')/255,y_train))
dataset=dataset.shuffle(buffer_size=1024).batch(64)


linear_layer = LinearV2(10)

#loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
#optimizer
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)


for step, (x,y) in enumerate(dataset):
    with tf.GradientTape() as tape:
        logits = linear_layer(x) #exp value
        print(x)
        loss = loss_fn(y,logits) #loss value (th,exp)

    gradients = tape.gradient(loss,linear_layer.trainable_weights) #gradient du loss
    #update des wieghts de notre layer
    optimizer.apply_gradients(zip(gradients,linear_layer.trainable_weights)) 
    
    if step % 100 ==0:
        print("Step:", step, "Loss:", float(loss))




tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
Step: 0 Loss: 2.4918935298919678
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]],

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


Step: 300 Loss: 2.1964879035949707
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


# Multiple layers

In [19]:
class MLP(keras.layers.Layer):
    """Simple stack of Linear layers"""
    
    def __init__(self):
        super(MLP, self).__init__()
        self.linear_1 = LinearV2(32)
        self.linear_2 = LinearV2(32)
        self.linear_3 = LinearV2(10)
        
    def call(self, inputs):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.linear_2(x)
        x = tf.nn.relu(x)
        return self.linear_3(x)
    
mlp = MLP()

y = mlp(tf.ones(shape=(3,64)))

assert len(mlp.weights) == 6

#print(mlp.weights)

In [20]:
mlp = keras.Sequential([keras.layers.Dense(32, activation=tf.nn.relu),keras.layers.Dense(32, activation=tf.nn.relu),keras.layers.Dense(10),])

y = mlp(tf.ones(shape=(3,64)))
assert len(mlp.weights) == 6

# Tracking losses 

In [21]:
class ActivityRegularization(keras.layers.Layer):
    """Layer that creates an activity sparsity regularization loss"""
    
    def __init__(self, rate=1e-2):
        super(ActivityRegularization, self).__init__()
        self.rate = rate
        
    def call(self, inputs):
        self.add_loss(self.rate*tf.reduce_sum(inputs))
        return inputs

In [22]:
class SparseMLP(keras.layers.Layer):
    """Stack of Linear layers with a sparsity regularization loss"""
    
    def __init__(self):
        super(SparseMLP, self).__init__()
        self.linear_1 = LinearV2(32)
        self.regularization = ActivityRegularization(1e-2)
        self.linear_3 = LinearV2(10)
        
    def call(self, inputs):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.regularization(x)
        return self.linear_3(x)
    
mlp = SparseMLP()
y = mlp(tf.ones((10,10)))

print(mlp.losses)

[<tf.Tensor: shape=(), dtype=float32, numpy=0.23265043>]


In [23]:
#losses correspond au dernier appel
mlp = SparseMLP()
mlp(tf.ones((10,10)))
assert len(mlp.losses) == 1
mlp(tf.ones((10,10)))
assert len(mlp.losses) == 1 #pas d'accumulation


#dataset
(x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices((x_train.reshape(60000,784).astype('float32')/255,y_train))
dataset=dataset.shuffle(buffer_size=1024).batch(64)
print(dataset)

mlp = SparseMLP()

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)


for step, (x,y) in enumerate(dataset):
    with tf.GradientTape() as tape:
        logits = mlp(x)
        loss = loss_fn(y, logits)
        loss += sum(mlp.losses)
        gradients = tape.gradient(loss, mlp.trainable_weights)
    
    optimizer.apply_gradients(zip(gradients, mlp.trainable_weights))
    
    with tf.GradientTape() as tape:
        logits_nc = mlp(x)
        loss_nc = loss_fn(y, logits_nc)
        gradients_nc = tape.gradient(loss_nc, mlp.trainable_weights)
        
    optimizer.apply_gradients(zip(gradients_nc, mlp.trainable_weights))
    
    if step % 100 == 0:
        print("Step:", step, "Loss:", float(loss), "Loss_nc", float(loss_nc))

<BatchDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.uint8, name=None))>
Step: 0 Loss: 6.747188568115234 Loss_nc 2.299862861633301
Step: 100 Loss: 2.5631790161132812 Loss_nc 2.303736686706543
Step: 200 Loss: 2.4472432136535645 Loss_nc 2.3000946044921875
Step: 300 Loss: 2.35219407081604 Loss_nc 2.296464443206787
Step: 400 Loss: 2.3465938568115234 Loss_nc 2.3063697814941406
Step: 500 Loss: 2.3306021690368652 Loss_nc 2.2992827892303467
Step: 600 Loss: 2.3551368713378906 Loss_nc 2.313190460205078
Step: 700 Loss: 2.3250367641448975 Loss_nc 2.305324077606201
Step: 800 Loss: 2.3315060138702393 Loss_nc 2.30964732170105
Step: 900 Loss: 2.311760663986206 Loss_nc 2.3037643432617188


# Training metric

In [24]:
#initialisation d'un objet metrique
accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

model = keras.Sequential([keras.layers.Dense(32,activation='relu'),keras.layers.Dense(32,activation='relu'),keras.layers.Dense(10),])

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)


for epoch in range(2):
    for step,(x,y) in enumerate(dataset):
        with tf.GradientTape() as tape:
            logits = model(x)
            loss_value = loss_fn(y,logits)
            print(loss_value)
            
        accuracy.update_state(y,logits)
        
        gradients = tape.gradient(loss_value, model.trainable_weights)
        optimizer.apply_gradients(zip(gradients, model.trainable_weights))
        
        if step % 200 == 0:
            print("Epoch:",epoch,"Step:",step)
            print("Loss:",float(loss_value),"Total running accuracy so far: %.3f" % accuracy.result())

tf.Tensor(2.3867235, shape=(), dtype=float32)
Epoch: 0 Step: 0
Loss: 2.386723518371582 Total running accuracy so far: 0.000
tf.Tensor(2.3211899, shape=(), dtype=float32)
tf.Tensor(2.2693017, shape=(), dtype=float32)
tf.Tensor(2.27238, shape=(), dtype=float32)
tf.Tensor(2.2416935, shape=(), dtype=float32)
tf.Tensor(2.263233, shape=(), dtype=float32)
tf.Tensor(2.246335, shape=(), dtype=float32)
tf.Tensor(2.1917017, shape=(), dtype=float32)
tf.Tensor(2.162787, shape=(), dtype=float32)
tf.Tensor(2.1465979, shape=(), dtype=float32)
tf.Tensor(2.0954099, shape=(), dtype=float32)
tf.Tensor(2.050219, shape=(), dtype=float32)
tf.Tensor(2.1029816, shape=(), dtype=float32)
tf.Tensor(2.0513082, shape=(), dtype=float32)
tf.Tensor(2.0387197, shape=(), dtype=float32)
tf.Tensor(2.0528042, shape=(), dtype=float32)
tf.Tensor(1.9934227, shape=(), dtype=float32)
tf.Tensor(1.9540248, shape=(), dtype=float32)
tf.Tensor(2.0677922, shape=(), dtype=float32)
tf.Tensor(1.8136959, shape=(), dtype=float32)
tf.Tenso

tf.Tensor(0.54610527, shape=(), dtype=float32)
tf.Tensor(0.48186308, shape=(), dtype=float32)
tf.Tensor(0.7583671, shape=(), dtype=float32)
tf.Tensor(0.39426073, shape=(), dtype=float32)
tf.Tensor(0.3063575, shape=(), dtype=float32)
tf.Tensor(0.5883766, shape=(), dtype=float32)
tf.Tensor(0.46520025, shape=(), dtype=float32)
tf.Tensor(0.3670711, shape=(), dtype=float32)
tf.Tensor(0.51241153, shape=(), dtype=float32)
tf.Tensor(0.65753794, shape=(), dtype=float32)
tf.Tensor(0.43067127, shape=(), dtype=float32)
tf.Tensor(0.50248855, shape=(), dtype=float32)
tf.Tensor(0.6493273, shape=(), dtype=float32)
tf.Tensor(0.48714608, shape=(), dtype=float32)
tf.Tensor(0.44388604, shape=(), dtype=float32)
tf.Tensor(0.625962, shape=(), dtype=float32)
tf.Tensor(0.47453582, shape=(), dtype=float32)
tf.Tensor(0.4003601, shape=(), dtype=float32)
tf.Tensor(0.3140521, shape=(), dtype=float32)
tf.Tensor(0.53153384, shape=(), dtype=float32)
tf.Tensor(0.5416078, shape=(), dtype=float32)
Epoch: 0 Step: 200
Loss

tf.Tensor(0.2225372, shape=(), dtype=float32)
tf.Tensor(0.5401395, shape=(), dtype=float32)
tf.Tensor(0.43343276, shape=(), dtype=float32)
tf.Tensor(0.4657359, shape=(), dtype=float32)
tf.Tensor(0.31765172, shape=(), dtype=float32)
tf.Tensor(0.48708132, shape=(), dtype=float32)
tf.Tensor(0.34673303, shape=(), dtype=float32)
tf.Tensor(0.7222545, shape=(), dtype=float32)
tf.Tensor(0.26873, shape=(), dtype=float32)
tf.Tensor(0.31237558, shape=(), dtype=float32)
tf.Tensor(0.24293096, shape=(), dtype=float32)
tf.Tensor(0.3799411, shape=(), dtype=float32)
tf.Tensor(0.35334164, shape=(), dtype=float32)
tf.Tensor(0.20444192, shape=(), dtype=float32)
tf.Tensor(0.42776084, shape=(), dtype=float32)
tf.Tensor(0.22073385, shape=(), dtype=float32)
tf.Tensor(0.36367232, shape=(), dtype=float32)
tf.Tensor(0.1415014, shape=(), dtype=float32)
tf.Tensor(0.22192664, shape=(), dtype=float32)
tf.Tensor(0.22994125, shape=(), dtype=float32)
tf.Tensor(0.2780645, shape=(), dtype=float32)
tf.Tensor(0.23037031, s

tf.Tensor(0.2699797, shape=(), dtype=float32)
tf.Tensor(0.21145181, shape=(), dtype=float32)
tf.Tensor(0.19786921, shape=(), dtype=float32)
tf.Tensor(0.25810683, shape=(), dtype=float32)
tf.Tensor(0.25582, shape=(), dtype=float32)
tf.Tensor(0.33805466, shape=(), dtype=float32)
tf.Tensor(0.11522249, shape=(), dtype=float32)
tf.Tensor(0.44098675, shape=(), dtype=float32)
tf.Tensor(0.29901016, shape=(), dtype=float32)
tf.Tensor(0.3177025, shape=(), dtype=float32)
tf.Tensor(0.22739285, shape=(), dtype=float32)
tf.Tensor(0.13576064, shape=(), dtype=float32)
tf.Tensor(0.16561617, shape=(), dtype=float32)
tf.Tensor(0.17801562, shape=(), dtype=float32)
tf.Tensor(0.34940273, shape=(), dtype=float32)
tf.Tensor(0.35950863, shape=(), dtype=float32)
tf.Tensor(0.18836816, shape=(), dtype=float32)
tf.Tensor(0.15570298, shape=(), dtype=float32)
tf.Tensor(0.26848832, shape=(), dtype=float32)
tf.Tensor(0.17684838, shape=(), dtype=float32)
tf.Tensor(0.2820671, shape=(), dtype=float32)
tf.Tensor(0.3668856

tf.Tensor(0.1851399, shape=(), dtype=float32)
tf.Tensor(0.28914943, shape=(), dtype=float32)
tf.Tensor(0.27528828, shape=(), dtype=float32)
tf.Tensor(0.2971639, shape=(), dtype=float32)
tf.Tensor(0.25758043, shape=(), dtype=float32)
tf.Tensor(0.25842032, shape=(), dtype=float32)
tf.Tensor(0.22995728, shape=(), dtype=float32)
tf.Tensor(0.27479634, shape=(), dtype=float32)
tf.Tensor(0.2690741, shape=(), dtype=float32)
tf.Tensor(0.4851488, shape=(), dtype=float32)
tf.Tensor(0.18121094, shape=(), dtype=float32)
tf.Tensor(0.18386808, shape=(), dtype=float32)
tf.Tensor(0.22008082, shape=(), dtype=float32)
tf.Tensor(0.28391105, shape=(), dtype=float32)
tf.Tensor(0.25440606, shape=(), dtype=float32)
tf.Tensor(0.26959643, shape=(), dtype=float32)
tf.Tensor(0.19638705, shape=(), dtype=float32)
tf.Tensor(0.13743772, shape=(), dtype=float32)
tf.Tensor(0.20749232, shape=(), dtype=float32)
tf.Tensor(0.48921728, shape=(), dtype=float32)
tf.Tensor(0.31619805, shape=(), dtype=float32)
tf.Tensor(0.16603

tf.Tensor(0.043849416, shape=(), dtype=float32)
tf.Tensor(0.1261418, shape=(), dtype=float32)
tf.Tensor(0.26276594, shape=(), dtype=float32)
tf.Tensor(0.16235377, shape=(), dtype=float32)
tf.Tensor(0.045241386, shape=(), dtype=float32)
tf.Tensor(0.15166187, shape=(), dtype=float32)
tf.Tensor(0.10723222, shape=(), dtype=float32)
tf.Tensor(0.113246664, shape=(), dtype=float32)
tf.Tensor(0.14286998, shape=(), dtype=float32)
tf.Tensor(0.16678524, shape=(), dtype=float32)
tf.Tensor(0.2338892, shape=(), dtype=float32)
tf.Tensor(0.035183683, shape=(), dtype=float32)
tf.Tensor(0.18657371, shape=(), dtype=float32)
tf.Tensor(0.12373675, shape=(), dtype=float32)
tf.Tensor(0.18797275, shape=(), dtype=float32)
tf.Tensor(0.31295902, shape=(), dtype=float32)
tf.Tensor(0.08865652, shape=(), dtype=float32)
tf.Tensor(0.04771764, shape=(), dtype=float32)
tf.Tensor(0.32821205, shape=(), dtype=float32)
tf.Tensor(0.3329433, shape=(), dtype=float32)
tf.Tensor(0.19264217, shape=(), dtype=float32)
tf.Tensor(0.

tf.Tensor(0.22531952, shape=(), dtype=float32)
tf.Tensor(0.3668847, shape=(), dtype=float32)
tf.Tensor(0.19918147, shape=(), dtype=float32)
tf.Tensor(0.1982398, shape=(), dtype=float32)
tf.Tensor(0.35871026, shape=(), dtype=float32)
tf.Tensor(0.16835847, shape=(), dtype=float32)
tf.Tensor(0.060634803, shape=(), dtype=float32)
tf.Tensor(0.12215176, shape=(), dtype=float32)
tf.Tensor(0.10601301, shape=(), dtype=float32)
tf.Tensor(0.24596956, shape=(), dtype=float32)
tf.Tensor(0.20293492, shape=(), dtype=float32)
tf.Tensor(0.07579127, shape=(), dtype=float32)
tf.Tensor(0.21927693, shape=(), dtype=float32)
tf.Tensor(0.3183053, shape=(), dtype=float32)
tf.Tensor(0.23701115, shape=(), dtype=float32)
tf.Tensor(0.19849354, shape=(), dtype=float32)
tf.Tensor(0.133439, shape=(), dtype=float32)
tf.Tensor(0.2690575, shape=(), dtype=float32)
tf.Tensor(0.17441079, shape=(), dtype=float32)
tf.Tensor(0.16158491, shape=(), dtype=float32)
tf.Tensor(0.2894262, shape=(), dtype=float32)
tf.Tensor(0.2278036

tf.Tensor(0.30044016, shape=(), dtype=float32)
tf.Tensor(0.077785626, shape=(), dtype=float32)
tf.Tensor(0.103973135, shape=(), dtype=float32)
tf.Tensor(0.16535097, shape=(), dtype=float32)
tf.Tensor(0.18693975, shape=(), dtype=float32)
tf.Tensor(0.27485442, shape=(), dtype=float32)
tf.Tensor(0.21659088, shape=(), dtype=float32)
tf.Tensor(0.09686442, shape=(), dtype=float32)
tf.Tensor(0.29905927, shape=(), dtype=float32)
tf.Tensor(0.19574368, shape=(), dtype=float32)
tf.Tensor(0.109034225, shape=(), dtype=float32)
tf.Tensor(0.25725567, shape=(), dtype=float32)
tf.Tensor(0.19251673, shape=(), dtype=float32)
tf.Tensor(0.33424824, shape=(), dtype=float32)
tf.Tensor(0.26489267, shape=(), dtype=float32)
tf.Tensor(0.12401175, shape=(), dtype=float32)
tf.Tensor(0.18973826, shape=(), dtype=float32)
tf.Tensor(0.21399373, shape=(), dtype=float32)
tf.Tensor(0.13256153, shape=(), dtype=float32)
tf.Tensor(0.24024768, shape=(), dtype=float32)
tf.Tensor(0.21177185, shape=(), dtype=float32)
tf.Tensor(

tf.Tensor(0.20920405, shape=(), dtype=float32)
tf.Tensor(0.07968525, shape=(), dtype=float32)
tf.Tensor(0.12143314, shape=(), dtype=float32)
tf.Tensor(0.11470892, shape=(), dtype=float32)
tf.Tensor(0.23784819, shape=(), dtype=float32)
tf.Tensor(0.15952514, shape=(), dtype=float32)
tf.Tensor(0.19179256, shape=(), dtype=float32)
tf.Tensor(0.18250558, shape=(), dtype=float32)
tf.Tensor(0.12528533, shape=(), dtype=float32)
tf.Tensor(0.15108356, shape=(), dtype=float32)
tf.Tensor(0.15578909, shape=(), dtype=float32)
tf.Tensor(0.17271364, shape=(), dtype=float32)
tf.Tensor(0.19913, shape=(), dtype=float32)
tf.Tensor(0.1410338, shape=(), dtype=float32)
tf.Tensor(0.35888696, shape=(), dtype=float32)
tf.Tensor(0.2789402, shape=(), dtype=float32)
tf.Tensor(0.29983044, shape=(), dtype=float32)
tf.Tensor(0.24572453, shape=(), dtype=float32)
tf.Tensor(0.1961951, shape=(), dtype=float32)
tf.Tensor(0.18110897, shape=(), dtype=float32)
tf.Tensor(0.05660125, shape=(), dtype=float32)
tf.Tensor(0.1440129

tf.Tensor(0.18361755, shape=(), dtype=float32)
tf.Tensor(0.23017433, shape=(), dtype=float32)
tf.Tensor(0.35870743, shape=(), dtype=float32)
tf.Tensor(0.21522057, shape=(), dtype=float32)
tf.Tensor(0.09942704, shape=(), dtype=float32)
tf.Tensor(0.3441465, shape=(), dtype=float32)
tf.Tensor(0.23290193, shape=(), dtype=float32)
tf.Tensor(0.27457765, shape=(), dtype=float32)
tf.Tensor(0.21122912, shape=(), dtype=float32)
tf.Tensor(0.15980777, shape=(), dtype=float32)
tf.Tensor(0.104087144, shape=(), dtype=float32)
tf.Tensor(0.0985212, shape=(), dtype=float32)
tf.Tensor(0.095536456, shape=(), dtype=float32)
tf.Tensor(0.16838676, shape=(), dtype=float32)
tf.Tensor(0.10588785, shape=(), dtype=float32)
tf.Tensor(0.25872928, shape=(), dtype=float32)
tf.Tensor(0.080599226, shape=(), dtype=float32)
tf.Tensor(0.26893565, shape=(), dtype=float32)
tf.Tensor(0.14807555, shape=(), dtype=float32)
tf.Tensor(0.08872263, shape=(), dtype=float32)
tf.Tensor(0.24674135, shape=(), dtype=float32)
tf.Tensor(0.

tf.Tensor(0.08918655, shape=(), dtype=float32)
tf.Tensor(0.09371985, shape=(), dtype=float32)
tf.Tensor(0.08800171, shape=(), dtype=float32)
tf.Tensor(0.186777, shape=(), dtype=float32)
tf.Tensor(0.15606931, shape=(), dtype=float32)
tf.Tensor(0.06093018, shape=(), dtype=float32)
tf.Tensor(0.068263665, shape=(), dtype=float32)
tf.Tensor(0.13604677, shape=(), dtype=float32)
tf.Tensor(0.050642677, shape=(), dtype=float32)
tf.Tensor(0.07027407, shape=(), dtype=float32)
tf.Tensor(0.14031202, shape=(), dtype=float32)
tf.Tensor(0.15167364, shape=(), dtype=float32)
tf.Tensor(0.10919592, shape=(), dtype=float32)
tf.Tensor(0.058446318, shape=(), dtype=float32)
tf.Tensor(0.10706668, shape=(), dtype=float32)
tf.Tensor(0.08145329, shape=(), dtype=float32)
tf.Tensor(0.05441908, shape=(), dtype=float32)
tf.Tensor(0.09038077, shape=(), dtype=float32)
tf.Tensor(0.109538406, shape=(), dtype=float32)
tf.Tensor(0.079300486, shape=(), dtype=float32)
tf.Tensor(0.056991193, shape=(), dtype=float32)
tf.Tensor

# Compiled functions

In [25]:
model = keras.Sequential([keras.layers.Dense(32,activation='relu'),keras.layers.Dense(32,activation='relu'),keras.layers.Dense(10),])

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)


#initialisation d'un objet metrique
accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

@tf.function
def train_on_batch(x,y):
    with tf.GradientTape() as tape:
        print(x)
        logits = model(x)
        loss = loss_fn(y,logits)
        gradients = tape.gradient(loss, model.trainable_weights)
    accuracy.update_state(y,logits)
    optimizer.apply_gradients(zip(gradients, model.trainable_weights))
    return loss


#dataset
(x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices((x_train.reshape(60000,784).astype('float32')/255,y_train))
dataset=dataset.shuffle(buffer_size=1024)
print(dataset)
dataset=dataset.batch(64)
print(dataset)

for step, (x,y) in enumerate(dataset):
    loss = train_on_batch(x,y)
    #if step % 100 ==0:
        #print('Step:',step,'Loss:',float(loss),"Running accuracy: %.3f" % accuracy.result())

<ShuffleDataset element_spec=(TensorSpec(shape=(784,), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.uint8, name=None))>
<BatchDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.uint8, name=None))>
Tensor("x:0", shape=(64, 784), dtype=float32)
Tensor("x:0", shape=(64, 784), dtype=float32)
Tensor("x:0", shape=(32, 784), dtype=float32)


# Interference mode

In [26]:
class Dropout(keras.layers.Layer):
    def __init__(self,rate):
        super(Dropout,self).__init__()
        self.rate = rate
        
    def call(self,inputs,training=None):
        if training:
            return tf.nn.dropout(inputs,rate=self.rate)
        return inputs

class MLPWithDropout(keras.layers.Layer):
    def __init__(self):
        super(MLPWithDropout,self).__init__()
        self.linear_1 = LinearV2(32)
        self.dropout = Dropout(0.5)
        self.linear_3 = LinearV2(10)
        
    def call(self,inputs,training=None):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.dropout(x,training=training)
        return self.linear_3(x)
    

mlp = MLPWithDropout()
y_train = mlp(tf.ones((2,2)),training=True)
y_test = mlp(tf.ones((2,2)),training=False)

print(y_train,'\n',y_test)

tf.Tensor(
[[ 0.03951059  0.0423923  -0.10195827 -0.06492737 -0.05196025  0.01823957
   0.02816523 -0.0629373   0.09912126 -0.02934749]
 [ 0.03978963  0.0529687  -0.15858448 -0.07807308 -0.05332524  0.01151394
  -0.00619519 -0.0229823   0.10320041  0.01451476]], shape=(2, 10), dtype=float32) 
 tf.Tensor(
[[ 0.03634857  0.02251479 -0.10859703 -0.09213449 -0.07333361  0.03107345
   0.02244956 -0.06226075  0.1008487  -0.02111857]
 [ 0.03634857  0.02251479 -0.10859703 -0.09213449 -0.07333361  0.03107345
   0.02244956 -0.06226075  0.1008487  -0.02111857]], shape=(2, 10), dtype=float32)


# Functional API

In [27]:
inputs = tf.keras.Input(shape=(16,),dtype='float32')

x = LinearV2(32)(inputs)
x = Dropout(0.5)(x)
outputs = LinearV2(10)(x)

model = tf.keras.Model(inputs,outputs)

assert len(model.weights) == 4

y = model(tf.ones((2,16)))
assert y.shape == (2,10)

y = model(tf.ones((2,16)), training=True)

In [28]:
inputs = tf.keras.Input(shape=(784,), dtype="float32")
x = keras.layers.Dense(32, activation="relu")(inputs)
x = keras.layers.Dense(32, activation="relu")(x)
outputs = keras.layers.Dense(10)(x)
model = tf.keras.Model(inputs, outputs)

model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),optimizer=keras.optimizers.Adam(learning_rate=1e-3),metrics=[keras.metrics.SparseCategoricalAccuracy()],)

print(dataset)

for x, y in dataset:
    print(x, y)
'''
model.fit(dataset, epochs=2)
model.predict(dataset)
model.evaluate(dataset)

model.summary() #etat model
'''

<BatchDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.uint8, name=None))>
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[4 4 6 1 7 6 9 3 9 5 3 0 9 0 9 1 5 0 2 7 4 1 5 1 8 6 0 5 3 7 0 1 7 7 8 0 9
 5 0 8 9 7 0 8 7 1 2 0 6 9 2 3 2 4 1 3 7 5 6 2 9 0 3 8], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[9 3 2 4 0 6 4 6 6 0 2 9 5 1 4 4 1 2 0 3 1 5 6 5 9 5 6 5 8 0 4 2 4 0 0 5 5
 1 1 1 5 7 2 4 2 9 1 7 0 4 2 6 2 0 1 1 6 0 1 7 5 4 7 7], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[0 5 7 7 4 9 8 6 8 4 4 9 6 3 3 4 9 1 9 0 7 0 0 7 2 5 0 9 2 2 1 6 0 8 3 3 1
 0 4 8 7 4 0 9 6 4 5 7 7 8 7 8 7 0 1 1 6 2 7 4 1 8 9 4], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[9 5 9 3 6 1 9 9 5 6 0 9 1 9 3 4 7 1 7 9 9 8 7 1 3 1 3 3 0 6 1 3 4 9 6 4 0
 6 6 9 8 5 0 2 3 0 6 6 7 0 8 0 9 2 3 8 0 5 0 0 2 8 8 3], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[2 4 8 0 5 9 9 0 4 7 3 7 6 1 2 4 1 2 1 7 5 8 2 1 1 

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[1 4 3 8 9 3 1 3 7 1 2 1 0 6 6 1 9 8 8 0 2 7 4 2 8 7 9 4 8 8 2 2 8 6 7 0 6
 0 7 8 0 9 8 1 0 5 3 0 5 8 1 2 3 9 8 9 1 7 2 2 3 5 4 0], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[8 1 8 0 5 0 0 1 5 9 5 9 0 5 7 3 3 6 8 8 8 9 6 2 1 9 3 5 4 9 8 3 4 6 0 2 9
 1 8 4 1 9 1 4 8 0 5 3 1 0 0 9 9 1 7 4 8 3 9 0 2 4 3 2], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[6 7 1 7 1 4 7 6 1 7 2 9 8 3 3 7 7 2 6 9 4 7 4 8 7 

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[1 4 5 7 3 5 0 3 2 3 9 4 7 6 2 8 4 7 1 3 3 1 8 6 5 9 1 5 7 9 4 6 6 9 6 0 4
 4 4 7 4 9 0 1 7 4 6 7 0 8 3 0 5 9 0 3 8 1 2 1 4 7 3 9], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[3 1 9 6 0 3 6 7 3 2 1 8 2 9 6 2 9 6 1 1 4 4 0 1 2 2 1 1 4 2 0 7 8 6 4 0 4
 6 7 4 2 9 9 0 1 3 1 1 9 7 3 3 3 2 0 0 7 2 7 1 1 5 9 1], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[6 1 9 2 3 9 3 4 2 3 8 8 7 8 7 9 1 9 0 6 3 4 4 2 1 

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[0 8 1 1 6 1 1 1 3 8 0 6 7 8 8 7 8 3 2 0 8 9 3 6 6 2 8 8 3 1 0 0 8 7 4 7 0
 2 2 2 1 3 1 8 1 6 9 6 7 3 8 8 3 7 2 0 0 1 4 3 4 3 4 0], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[9 7 7 3 3 5 9 1 0 2 7 4 4 9 8 3 3 7 1 6 8 3 8 5 4 0 1 1 6 2 1 2 3 3 4 3 4
 0 9 5 5 6 6 8 9 3 1 4 3 7 3 4 1 5 3 6 0 4 8 9 0 4 8 3], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[1 3 3 6 8 6 5 0 9 8 8 6 5 7 2 1 8 3 4 7 7 7 2 5 2 

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[7 0 2 8 3 7 8 3 0 5 0 2 8 2 3 7 1 5 3 6 3 7 8 8 1 0 4 7 1 2 4 9 9 0 8 4 5
 9 9 8 2 1 5 0 8 7 5 7 2 9 1 1 6 8 2 7 9 7 6 6 2 6 9 4], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[2 6 2 6 8 3 9 5 6 7 5 4 0 5 9 3 1 4 2 0 1 5 5 9 3 6 0 7 3 4 8 2 8 3 3 3 0
 9 4 2 6 6 5 9 9 3 1 7 1 8 2 0 2 1 2 4 4 4 6 8 1 0 7 4], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[7 0 3 3 1 5 3 5 9 2 8 4 0 4 9 7 6 8 1 9 4 4 8 7 3 

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[9 8 7 9 3 5 2 3 3 7 9 2 1 6 7 8 1 1 8 5 7 8 1 9 8 0 3 6 5 3 2 9 2 0 9 5 6
 4 0 7 8 2 0 0 9 0 9 6 7 2 3 5 6 7 8 7 2 6 1 7 0 9 2 2], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[0 0 3 7 2 7 7 3 2 2 5 8 2 1 8 2 3 7 6 2 3 2 4 8 0 2 0 7 6 9 8 9 8 6 0 6 6
 8 9 7 8 6 5 3 1 2 2 3 8 0 6 1 7 7 5 5 0 1 0 2 2 6 1 4], shape=(64,), dtype=uint8)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32) tf.Tensor(
[3 8 7 7 2 3 1 0 4 0 0 6 6 5 5 6 6 9 6 8 5 0 4 3 0 

'\nmodel.fit(dataset, epochs=2)\nmodel.predict(dataset)\nmodel.evaluate(dataset)\n\nmodel.summary() #etat model\n'

In [29]:
class CustomModel(keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.loss_tracker = keras.metrics.Mean(name='loss')
        self.accuracy = keras.metrics.SparseCategoricalAccuracy()
        self.loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
        self.optimizer = keras.optimizers.Adam(learning_rate=1e-3)
        
    def train_step(self, data):
        x,y=data
        with tf.GradientTape() as tape:
            y_pred = self(x, training = True)
            loss = self.loss_fn(y,y_pred)
        gradients = tape.gradient(loss,self.trainable_weights)
        self.optimizer.apply_gradients(zip(gradients,self.trainable_weights))
        self.loss_tracker.update_state(loss)
        self.accuracy.update_state(y,y_pred)
        return {"loss": self.loss_tracker.result(), "accuracy": self.accuracy.result()}
    
    @property
    def metrics(self):
        return [self.loss_tracker, self.accuracy]
    

inputs = tf.keras.Input(shape=(784,), dtype="float32")
x = keras.layers.Dense(32, activation="relu")(inputs)
x = keras.layers.Dense(32, activation="relu")(x)
outputs = keras.layers.Dense(10)(x)

model = CustomModel(inputs, outputs)

model.compile()
model.fit(dataset, epochs=2)

model.summary()

Epoch 1/2
938/938 [==============================] - 3s 3ms/step - loss: 0.4035 - accuracy: 0.8173
Epoch 2/2
938/938 [==============================] - 3s 3ms/step - loss: 0.2086 - accuracy: 0.9349
Model: "custom_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_12 (Dense)            (None, 32)                25120     
                                                                 
 dense_13 (Dense)            (None, 32)                1056      
                                                                 
 dense_14 (Dense)            (None, 10)                330       
                                                                 
Total params: 26,510
Trainable params: 26,506
Non-trainable params: 4
__________________________________________________

In [35]:
y_true = [1, 2]
y_pred = [[0.05, 0.95, 0.1], [0.1, 0.8, 0.1]]
# Using 'auto'/'sum_over_batch_size' reduction type.
scce = tf.keras.losses.SparseCategoricalCrossentropy()
print(y_true[0],y_pred[0])
scce(y_true[0], y_pred[0]).numpy()


1 [0.05, 0.95, 0.1]


0.14660347